services:
  web:
    image: ghcr.io/ostefanini/ts-drones/web:latest
    container_name: "web"
    volumes:
      - ./certs:/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      api:
        condition: service_started

  api:
    image: ghcr.io/ostefanini/ts-drones/api:latest
    container_name: "api"
    ports:
      - 127.0.0.1:4000:4000
